### ISSUE TITLE
Standard docs bulid failing on setup.py

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/sphinxcontrib-opencontracting#21]
I'm try to get the standard docs build running locally but getting the following error when installing requirements

```
Command "python setup.py egg_info" failed with error code 1 in /home/ddewhurst/.pyenv/versions/3.6.0/envs/standard/src/sphinxcontrib-opencontracting/
```

I'm using a fresh Python 3.6.0 environment

**Comment by jpmckinney** [comment]
Can you provide more context/lines of what you see in the terminal?

**Comment by duncandewhurst** [comment]
Here's the output from `pip install -r requirements.txt` for sphinxcontrib-opencontracting, all other requirements install successfully:

```
Obtaining sphinxcontrib-opencontracting from git+https://github.com/open-contracting/sphinxcontrib-opencontracting.git@d8271541fbf7385035e8a160f73886d8184daaa7#egg=sphinxcontrib-opencontracting (from -r requirements.txt (line 5))
  Skipping because already up-to-date.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ddewhurst/.pyenv/versions/3.6.0/envs/standard/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "/home/ddewhurst/.pyenv/versions/3.6.0/envs/standard/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/home/ddewhurst/.pyenv/versions/3.6.0/envs/standard/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
        @_call_aside
      File "/home/ddewhurst/.pyenv/versions/3.6.0/envs/standard/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "/home/ddewhurst/.pyenv/versions/3.6.0/envs/standard/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "/home/ddewhurst/.pyenv/versions/3.6.0/envs/standard/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "/home/ddewhurst/.pyenv/versions/3.6.0/envs/standard/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/ddewhurst/.pyenv/versions/3.6.0/envs/standard/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/home/ddewhurst/.pyenv/versions/3.6.0/envs/standard/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/ddewhurst/.pyenv/versions/3.6.0/envs/standard/src/sphinxcontrib-opencontracting/

```

**Comment by duncandewhurst** [comment]
I created a Pyhton 3.6.9 virtualenv and it works OK in that

**Comment by jpmckinney** [comment]
Yeah, it seems to be an issue with bad versions of pip and setuptools.
